language: ruby
before_install: "gem install rjack-tarpit -v'~>2.1' || \
      ( sleep 1; gem install rjack-tarpit -v'~>2.1' ) || \
      ( sleep 5; gem install rjack-tarpit -v'~>2.1' )"
bundler_args: ""
script: "bundle exec rake test"
sudo: false
matrix:
  include:
    - rvm: jruby-1.7.20
      jdk: openjdk7
      gemfile: Gemfile.92
    - rvm: jruby-1.7.20
      jdk: oraclejdk8
    - rvm: jruby-9.0.4.0
      jdk: oraclejdk8
    - rvm: jruby-head
      jdk: oraclejdk8
  allow_failures:
    - rvm: jruby-head
