language: ruby
before_install: "gem install rjack-tarpit -v'~>2.1' || \
      ( sleep 1; gem install rjack-tarpit -v'~>2.1' ) || \
      ( sleep 5; gem install rjack-tarpit -v'~>2.1' )"
bundler_args: ""
script: "bundle exec rake test"
matrix:
  include:
    - rvm: jruby
      jdk: openjdk7
      gemfile: Gemfile.92
    - rvm: jruby
      jdk: oraclejdk8
      gemfile: Gemfile
    - rvm: jruby-9.0.0.0.pre2
      jdk: oraclejdk8
      gemfile: Gemfile
  allow_failures:
    - rvm: jruby-9.0.0.0.pre2
