language: ruby
before_install: "gem install rjack-tarpit -v=2.1.2"
install: "bundle install --jobs=3 --retry=3"
sudo: false
script: "bundle exec rake test"
dist: trusty
matrix:
  include:
    - rvm: jruby-1.7.26
      jdk: openjdk7
      gemfile: Gemfile.92
      dist: precise
    - rvm: jruby-9.1.9.0
      jdk: oraclejdk8
      gemfile: Gemfile.93
    - rvm: jruby-9.1.9.0
      jdk: oraclejdk8
    - rvm: jruby-9.1.9.0
      jdk: openjdk8
    - rvm: jruby-head
      jdk: oraclejdk8
  allow_failures:
    - rvm: jruby-head
