language: ruby
before_install:
 - "gem install rjack-tarpit -v'~>2.1' || \
     ( sleep 1; gem install rjack-tarpit -v'~>2.1' ) || \
     ( sleep 5; gem install rjack-tarpit -v'~>2.1' )"
 - "gem install bundler --version 1.13.7"
install: "bundle _1.13.7_ install --retry=3"
script: "bundle _1.13.7_ exec rake test"
sudo: false
matrix:
  include:
    - rvm: jruby-1.7.26
      jdk: openjdk7
      gemfile: Gemfile.92
    - rvm: jruby-9.1.7.0
      jdk: oraclejdk8
    - rvm: jruby-head
      jdk: oraclejdk8
  allow_failures:
    - rvm: jruby-head
