language: ruby
before_install: "gem install rjack-tarpit -v'~>2.1' || \
      ( sleep 1; gem install rjack-tarpit -v'~>2.1' ) || \
      ( sleep 5; gem install rjack-tarpit -v'~>2.1' )"
bundler_args: ""
rvm:
  - jruby-1.7.20
  - jruby-head
jdk:
  - openjdk7
  - oraclejdk8
gemfile:
  - Gemfile
  - Gemfile.92
script: "bundle exec rake test"
matrix:
  include:
    - rvm: jruby-1.7.20
      jdk: openjdk7
      gemfile: Gemfile.92
    - rvm: jruby-1.7.20
      jdk: oraclejdk8
      gemfile: Gemfile
    - rvm: jruby-head
      jdk: oraclejdk8
      gemfile: Gemfile
  allow_failures:
    - rvm: jruby-head
